# Generated by Django 4.0.6 on 2022-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics'),
        ),
    ]
