# Generated by Django 4.0.6 on 2022-08-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_catalog_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='catalog_pics/default.jp/', upload_to='catalog_pics'),
        ),
    ]
