# Generated by Django 4.0.6 on 2022-08-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='catalog_pics/default.jpg', upload_to='catalog_pics'),
        ),
    ]
