# Generated by Django 4.0.6 on 2022-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='catalog_pics/default.jpg', upload_to='static/img/'),
        ),
    ]
