# Generated by Django 4.0.6 on 2022-08-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics'),
        ),
    ]
