# Generated by Django 4.0.6 on 2022-08-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='catalog_pics/default.jpg', upload_to='catalog_pics/'),
        ),
    ]
