# Generated by Django 4.0.6 on 2022-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_catalog_category_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Ссылка'),
        ),
    ]
